name: cleanup

# triggered whenever a PR submitted to master is merged or closed
on:
  pull_request:
    types: [closed]   
    branches:
      - master

jobs:
  build:
    name: cleanup
    runs-on: ubuntu-latest
    env:
      PULL_FOLDER: pull_${{ github.event.pull_request.number }}
    steps:
      # checkout at gh-pages branch
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      # check if folder for this pull request exists
      - name: Check folder existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ env.PULL_FOLDER }}

      # delete the corresponding pull request doc folder
      - name: Delete folder
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo the folder $PULL_FOLDER will be deleted
          if [ -d "$PULL_FOLDER" ]; then rm -Rf $PULL_FOLDER; fi

      # force push the deletion to gp-pages
      - name: Deploy docs
        if: success() && steps.check_files.outputs.files_exists == 'true'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./
          keep_history: false  
        env:
          GH_PAT: ${{ secrets.GH_PAT }}