name: docs

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build and deploy docs
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{secrets.GH_PAT}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython --install-option="--no-cython-compile"
      - name: Install
        run: |
          python -m pip install --no-cache-dir -r requirements-dev.txt
      - name: Generate docs
        if: ${{ success() }}
        run: |
          invoke docs
          # Get branch/tag/latest name from git
          GITHUB_REF_REGEX="tags/v([0-9a-zA-Z\.\-]+)|(pull/[0-9]+)|heads/(.+)"
          if [[ $GITHUB_REF =~ $GITHUB_REF_REGEX ]]; then
            if [[ $BASH_REMATCH = pull* ]]; then
              BRANCH_OR_TAG=pull_${BASH_REMATCH##*/}
            else
              BRANCH_OR_TAG=${BASH_REMATCH##*/v}
            fi;
            if [[ $BRANCH_OR_TAG = master ]]; then
              BRANCH_OR_TAG=latest
            fi;
          fi;
          echo "Docs will be deployed to https://blockresearchgroup.github.io/compas_ags/$BRANCH_OR_TAG"
          mkdir -p deploy/$BRANCH_OR_TAG && mv -T dist/docs deploy/$BRANCH_OR_TAG/
      - name: Deploy docs
        if: success() && env.GH_PAT != ''
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: deploy
          keep_history: true
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  docVersions:
    needs: build
    name: update doc versions
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{secrets.GH_PAT}}
    steps:

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: update doc versions
        run: |
          >doc_versions.txt
          for folder in $(ls -rd */ | tr -d '/')
          do 
              if [[ $folder =~ ^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$|^latest$ ]]
              then 
                  echo ${folder}  >> doc_versions.txt
              fi
          done
          echo found available doc versions:
          cat doc_versions.txt

      - name: Deploy docs
        if: success() && env.GH_PAT != ''
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./
          keep_history: false  
        env:
          GH_PAT: ${{ secrets.GH_PAT }}